<?php

declare(strict_types=1);

namespace CoquiBot\Coqui\Config;

use CarmeloSantana\PathHelper\PathHelper;
use CoquiBot\Coqui\Exception\SkillParseException;

/**
 * Derives the documentation index from disk.
 *
 * Structure is globbed, never listed: every `docs/*.md` plus README.md and
 * AGENTS.md is indexed the moment the file exists. A hardcoded allowlist here
 * previously hid eight docs — including LOOPS.md and PERSONAS.md — from the
 * agent, so the file list must stay derived.
 *
 * Intent is authored where it belongs: per-doc title/description come from the
 * doc's own frontmatter, falling back to its H1 and first paragraph.
 *
 * @phpstan-type DocSection array{heading: string, level: int, line_start: int, line_end: int}
 * @phpstan-type DocFile array{path: string, title: string, description: string, sections: list<DocSection>}
 * @phpstan-type DocIndex array{version: string, files: list<DocFile>}
 */
final class DocumentationIndex
{
    public const string VERSION = '1.0.0';

    /** Docs that live at the project root rather than under docs/. */
    private const array ROOT_DOCS = ['README.md', 'AGENTS.md'];

    private readonly string $normalizedRoot;

    private readonly SkillParser $frontmatter;

    public function __construct(
        string $projectRoot,
        ?SkillParser $frontmatter = null,
    ) {
        $this->normalizedRoot = PathHelper::trimTrailingSlash($projectRoot);
        $this->frontmatter = $frontmatter ?? new SkillParser();
    }

    /**
     * Load the generated index, deriving it from disk if unavailable.
     *
     * config/documentation.json is a build-time cache: it is git-ignored and
     * generated by release/Docker builds, so a fresh checkout has none. A
     * missing cache must degrade to a slower path, never to a dead tool.
     *
     * @return DocIndex
     */
    public function load(): array
    {
        $cached = $this->readGenerated();

        return $cached ?? $this->build();
    }

    /**
     * Derive the index by globbing and parsing the docs on disk.
     *
     * @return DocIndex
     */
    public function build(): array
    {
        $files = [];

        foreach ($this->docPaths() as $relativePath) {
            $entry = $this->buildEntry($relativePath);

            if ($entry !== null) {
                $files[] = $entry;
            }
        }

        return ['version' => self::VERSION, 'files' => $files];
    }

    /**
     * Every indexable doc path, relative to the project root, sorted.
     *
     * Only docs/*.md — not docs/**\/*.md — so working artefacts such as
     * docs/superpowers/{specs,plans} stay out of the agent's index.
     *
     * @return list<string>
     */
    private function docPaths(): array
    {
        $matches = glob($this->normalizedRoot . '/docs/*.md') ?: [];
        sort($matches);

        $paths = [];

        foreach ($matches as $absolute) {
            $paths[] = 'docs/' . basename($absolute);
        }

        foreach (self::ROOT_DOCS as $rootDoc) {
            if (is_file($this->normalizedRoot . '/' . $rootDoc)) {
                $paths[] = $rootDoc;
            }
        }

        return $paths;
    }

    /**
     * @return DocFile|null
     */
    private function buildEntry(string $relativePath): ?array
    {
        $absolute = $this->normalizedRoot . '/' . $relativePath;
        $content = file_get_contents($absolute);

        if ($content === false) {
            return null;
        }

        $lines = file($absolute, FILE_IGNORE_NEW_LINES);

        if ($lines === false) {
            return null;
        }

        $sections = $this->extractSections($lines);
        $meta = $this->extractMetadata($content, $sections, $relativePath);

        return [
            'path' => $relativePath,
            'title' => $meta['title'],
            'description' => $meta['description'],
            'sections' => $sections,
        ];
    }

    /**
     * Resolve title/description from frontmatter, falling back to H1 + first paragraph.
     *
     * @param list<DocSection> $sections
     *
     * @return array{title: string, description: string}
     */
    private function extractMetadata(string $content, array $sections, string $relativePath): array
    {
        $body = $content;
        $title = null;
        $description = null;

        try {
            $parsed = $this->frontmatter->parseFrontmatter($content);
            $body = $parsed['body'];

            $meta = $parsed['metadata'];

            if (isset($meta['title']) && is_string($meta['title']) && $meta['title'] !== '') {
                $title = $meta['title'];
            }

            if (isset($meta['description']) && is_string($meta['description']) && $meta['description'] !== '') {
                $description = $meta['description'];
            }
        } catch (SkillParseException) {
            // No frontmatter — expected for docs that have not adopted it yet.
        }

        return [
            'title' => $title ?? $this->firstH1($sections) ?? basename($relativePath),
            'description' => $description ?? $this->firstParagraph($body) ?? '',
        ];
    }

    /**
     * The first H1 from the section list, or null.
     *
     * Derived from the sections rather than re-scanned, so the title inherits
     * extractSections' fence awareness instead of needing a second tracker.
     *
     * @param list<DocSection> $sections
     */
    private function firstH1(array $sections): ?string
    {
        foreach ($sections as $section) {
            if ($section['level'] === 1) {
                return trim($section['heading'], " `");
            }
        }

        return null;
    }

    /**
     * The first prose paragraph in the body, or null.
     *
     * Skips headings, fenced code, and HTML. README.md cannot carry frontmatter
     * — GitHub renders it as a visible table on the repo front page — so this
     * fallback is the only thing standing between the agent and a description of
     * "<!-- markdownlint-disable MD033 -->".
     */
    private function firstParagraph(string $body): ?string
    {
        $inCodeBlock = false;
        $inHtmlComment = false;
        $inHtmlBlock = false;

        foreach (explode("\n", $body) as $line) {
            $trimmed = trim($line);

            // Comments run to their terminator across any number of lines.
            if ($inHtmlComment) {
                $inHtmlComment = !str_contains($trimmed, '-->');
                continue;
            }

            if (str_starts_with($trimmed, '```')) {
                $inCodeBlock = !$inCodeBlock;
                continue;
            }

            if ($inCodeBlock) {
                continue;
            }

            // An HTML block closes at the next blank line, so the text inside it
            // (badge rows, centred link lists) never wins over the real intro.
            if ($inHtmlBlock) {
                $inHtmlBlock = $trimmed !== '';
                continue;
            }

            if (str_starts_with($trimmed, '<!--')) {
                $inHtmlComment = !str_contains(substr($trimmed, 4), '-->');
                continue;
            }

            if (preg_match('/^<\/?[a-zA-Z]/', $trimmed) === 1) {
                $inHtmlBlock = true;
                continue;
            }

            if ($trimmed === '' || str_starts_with($trimmed, '#')) {
                continue;
            }

            return $trimmed;
        }

        return null;
    }

    /**
     * Extract H1–H4 headings with 1-based line ranges against the file on disk.
     *
     * Line numbers stay absolute (frontmatter included) because coqui_docs_read
     * slices the raw file by these ranges.
     *
     * @param list<string> $lines
     *
     * @return list<DocSection>
     */
    private function extractSections(array $lines): array
    {
        $headings = [];
        $inCodeBlock = false;

        foreach ($lines as $i => $line) {
            if (str_starts_with($line, '```')) {
                $inCodeBlock = !$inCodeBlock;
                continue;
            }

            if ($inCodeBlock) {
                continue;
            }

            if (preg_match('/^(#{1,4})\s+(.+)$/', $line, $matches) === 1) {
                $headings[] = [
                    'heading' => trim($matches[2]),
                    'level' => strlen($matches[1]),
                    'line_start' => $i + 1,
                ];
            }
        }

        $totalLines = count($lines);
        $sections = [];
        $count = count($headings);

        for ($i = 0; $i < $count; $i++) {
            $sections[] = [
                'heading' => $headings[$i]['heading'],
                'level' => $headings[$i]['level'],
                'line_start' => $headings[$i]['line_start'],
                'line_end' => $i + 1 < $count
                    ? $headings[$i + 1]['line_start'] - 1
                    : $totalLines,
            ];
        }

        return $sections;
    }

    /**
     * Read the generated index, or null when absent/unreadable/malformed/stale.
     *
     * @return DocIndex|null
     */
    private function readGenerated(): ?array
    {
        $path = $this->normalizedRoot . '/config/documentation.json';

        if (!is_file($path)) {
            return null;
        }

        $content = file_get_contents($path);

        if ($content === false) {
            return null;
        }

        $data = json_decode($content, true);

        if (!is_array($data) || !isset($data['files']) || !is_array($data['files'])) {
            return null;
        }

        // VERSION is pinned so a cache written against a different index shape is
        // rebuilt rather than trusted. Without this the cast below is a lie: a
        // versionless cache flows out typed as DocIndex with no version key.
        if (!isset($data['version']) || $data['version'] !== self::VERSION) {
            return null;
        }

        // The file list is derived, so a cache that disagrees with disk is stale:
        // it would offer a renamed or deleted doc and hide a new one. Content
        // edits are not detected — see CoquiDocsToolkit::extractSectionFromFile.
        $cachedPaths = array_column($data['files'], 'path');
        $diskPaths = $this->docPaths();
        sort($cachedPaths);
        sort($diskPaths);

        if ($cachedPaths !== $diskPaths) {
            return null;
        }

        /** @var DocIndex $data */
        return $data;
    }
}
